;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Active.Roll",DevComment="")
+GameplayTagList=(Tag="Ability.Active.Sprint",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dodge",DevComment="")
+GameplayTagList=(Tag="Event.Energy.Empty",DevComment="")
+GameplayTagList=(Tag="Status.Invulnerable.ByDodge",DevComment="")

