;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ability.Active.MeleeAttack.FrontCut",NewTagName="Ability.Active.MeleeAttack.SideCut")
+GameplayTagRedirects=(OldTagName="CombatStyle.Spellcasting",NewTagName="CombatStyle.Spells")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack.GrapplingSlash",DevComment="")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack.HeadSeverer",DevComment="")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack.PristineCut",DevComment="")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack.SharkSlash",DevComment="")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack.SideCut",DevComment="")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack.UpFinisher",DevComment="")
+GameplayTagList=(Tag="Ability.Active.MeleeAttack.UpSwing",DevComment="")
+GameplayTagList=(Tag="Ability.Active.Roll",DevComment="")
+GameplayTagList=(Tag="Ability.Active.Sprint",DevComment="")
+GameplayTagList=(Tag="Ability.Reaction.BeingHit",DevComment="")
+GameplayTagList=(Tag="Ability.Reaction.Death",DevComment="")
+GameplayTagList=(Tag="CombatStyle.Archery",DevComment="")
+GameplayTagList=(Tag="CombatStyle.Lance",DevComment="")
+GameplayTagList=(Tag="CombatStyle.Spells",DevComment="")
+GameplayTagList=(Tag="CombatStyle.Spells.Spellcasting",DevComment="")
+GameplayTagList=(Tag="CombatStyle.Sword",DevComment="")
+GameplayTagList=(Tag="CombatStyle.Sword.DualWielding",DevComment="")
+GameplayTagList=(Tag="CombatStyle.Sword.SingleSword",DevComment="")
+GameplayTagList=(Tag="CombatStyle.Sword.SwordAndSorcery",DevComment="")
+GameplayTagList=(Tag="CombatStyle.TwoHanded",DevComment="")
+GameplayTagList=(Tag="CombatStyle.TwoHanded.Greatsword",DevComment="")
+GameplayTagList=(Tag="CombatStyle.TwoHanded.Hammer",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dodge",DevComment="")
+GameplayTagList=(Tag="Data.CriticalMultiplier",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Experience",DevComment="")
+GameplayTagList=(Tag="Data.Sun",DevComment="")
+GameplayTagList=(Tag="Event.Attack.HitEnd",DevComment="")
+GameplayTagList=(Tag="Event.Attack.HitStart",DevComment="")
+GameplayTagList=(Tag="Event.Attack.NextAttackReady",DevComment="")
+GameplayTagList=(Tag="Event.Energy.Empty",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.BeingHit",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Status.EnergyRegenerationBlocked",DevComment="")
+GameplayTagList=(Tag="Status.HyperArmor",DevComment="")
+GameplayTagList=(Tag="Status.Invulnerable.ByDodge",DevComment="")
+GameplayTagList=(Tag="Status.MovementLocked",DevComment="")

